name: Release
on:
  workflow_dispatch:
env:
  MAJOR: 1
  MINOR: 0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      EXECUTABLE_NAME: ${{ steps.set_output.outputs.EXECUTABLE_NAME }}
      VERSION: "${{ env.MAJOR }}.${{ env.MAJOR }}.${{ github.run_number }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set EXECUTABLE_NAME
        id: set_output
        run: |
          sudo apt-get install jq
          echo "::set-output name=EXECUTABLE_NAME::$(jq '.name' .changelogrc | tr -d '"')"
  build_release:
    needs: [setup]
    strategy:
      matrix:
        include:
          - {
              rust: stable,
              os: ubuntu-latest,
              useCross: true,
              target: x86_64-unknown-linux-musl,
              suffix: "",
            }
          - {
              rust: stable,
              os: macos-latest,
              useCross: false,
              target: x86_64-apple-darwin,
              suffix: "",
            }
          - {
              rust: stable,
              os: windows-latest,
              useCross: false,
              target: x86_64-pc-windows-msvc,
              suffix: .exe,
            }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli
          version: latest
          use-tool-cache: true
      - shell: bash
        env:
          VERSION: ${{ needs.setup.outputs.VERSION }}
        run: |
          TEMP_FILE="$(mktemp)"
          toml set Cargo.toml package.version "$VERSION" > "$TEMP_FILE"
          mv "$TEMP_FILE" Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.useCross }}
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/${{ needs.setup.outputs.EXECUTABLE_NAME }}${{ matrix.suffix }}
          if-no-files-found: error

  release:
    needs: [build_release, setup]
    env:
      LINUX_EXE: artifacts/x86_64-unknown-linux-musl/changelog-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts/
      - shell: bash
        name: Zip exes
        id: zip_exes
        run: |
          shopt -s globstar
          shopt -s extglob
          cd artifacts/
          for input in $(ls -d -- **/changelog-cli?(.*)); do
          chmod +x $input
          zip -j "$(basename $(dirname $input)).zip" $input
          done
      - name: Generate Changelog
        id: generate_changelog
        run: |
          ${{ env.LINUX_EXE }} merge -v ${{needs.setup.outputs.VERSION}} -d
          git log
      # - name: Create Release
      #   id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   run: |
      #     gh release create v${{ needs.setup.outputs.VERSION }} -t v${{ needs.setup.outputs.VERSION }} -F CHANGELOG.md ./artifacts/*.zip --target ${{ github.sha }}
      - name: Push removed changed files
        id: commit_changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force
